[workspace]
members = [
    "ieee754",
    "ieee754_unit_tests",
    "test_packages/ieee754_test_add_cancellation",
    "test_packages/ieee754_test_add_cancellation_and_subnorm_result",
    "test_packages/ieee754_test_add_shift",
    "test_packages/ieee754_test_add_shift_and_special_significands_part0",
    "test_packages/ieee754_test_add_shift_and_special_significands_part1",
    "test_packages/ieee754_test_add_shift_and_special_significands_part10",
    "test_packages/ieee754_test_add_shift_and_special_significands_part11",
    "test_packages/ieee754_test_add_shift_and_special_significands_part12",
    "test_packages/ieee754_test_add_shift_and_special_significands_part13",
    "test_packages/ieee754_test_add_shift_and_special_significands_part14",
    "test_packages/ieee754_test_add_shift_and_special_significands_part15",
    "test_packages/ieee754_test_add_shift_and_special_significands_part16",
    "test_packages/ieee754_test_add_shift_and_special_significands_part17",
    "test_packages/ieee754_test_add_shift_and_special_significands_part18",
    "test_packages/ieee754_test_add_shift_and_special_significands_part19",
    "test_packages/ieee754_test_add_shift_and_special_significands_part2",
    "test_packages/ieee754_test_add_shift_and_special_significands_part20",
    "test_packages/ieee754_test_add_shift_and_special_significands_part21",
    "test_packages/ieee754_test_add_shift_and_special_significands_part22",
    "test_packages/ieee754_test_add_shift_and_special_significands_part23",
    "test_packages/ieee754_test_add_shift_and_special_significands_part24",
    "test_packages/ieee754_test_add_shift_and_special_significands_part25",
    "test_packages/ieee754_test_add_shift_and_special_significands_part26",
    "test_packages/ieee754_test_add_shift_and_special_significands_part3",
    "test_packages/ieee754_test_add_shift_and_special_significands_part4",
    "test_packages/ieee754_test_add_shift_and_special_significands_part5",
    "test_packages/ieee754_test_add_shift_and_special_significands_part6",
    "test_packages/ieee754_test_add_shift_and_special_significands_part7",
    "test_packages/ieee754_test_add_shift_and_special_significands_part8",
    "test_packages/ieee754_test_add_shift_and_special_significands_part9",
    "test_packages/ieee754_test_basic_types_inputs_part0",
    "test_packages/ieee754_test_basic_types_inputs_part1",
    "test_packages/ieee754_test_basic_types_inputs_part2",
    "test_packages/ieee754_test_basic_types_intermediate",
    "test_packages/ieee754_test_corner_rounding",
    "test_packages/ieee754_test_divide_divide_by_zero_exception",
    "test_packages/ieee754_test_divide_trailing_zeros",
    "test_packages/ieee754_test_hamming_distance",
    "test_packages/ieee754_test_input_special_significand",
    "test_packages/ieee754_test_overflow",
    "test_packages/ieee754_test_rounding",
    "test_packages/ieee754_test_underflow",
    "test_packages/ieee754_test_vicinity_of_rounding_boundaries"
]
